### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by Niklp09** [Archtec-io/archtec-mods#56]
- [x] ATM Mod: unregister items 
- [x] remove the beacon mod
- [x] darkage mapgen entfernen
:x: emotes
- [x] facade fork mit not_in_creative_inventory
- [x] stained_glass 
- [x] content.minetest.net/packages/X17/invisible_wall/ as a git repo
- [x] mobs_redo over notabug
- [x] chatplus moderator unabhängig machen sowie priv neu definieren
- [x] myblocks brick in vllt graystone integrieren?
- [x] firework mod
- [x] eigene rank mod
:x: rules mod auf git hochladen
- [x] technic_cnc fork hochladen und technic_chests rewriten
- [x] teleport_request neuschreiben
- [x] dummies mod auf git hochladen
- [x] scifi_nodes(_unregister)
- [x] upload letters
- [x] feldweg obj files wieder einfügen (wo sind die hin?!)
- [x] darkage facade kompatibilität herstellen
- [x] git.minetest.org/GreenXenith/windchimes hinzufügen
- [x] 3d_armor adden
- [x] wield_3d
- [x] redo technic_cnc
- [x] add cblocks
- [x] add archtec custom
